name: Compile ALNILAM
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      java-version: 
        required: true
        type: string
        
jobs:
  Compile-ALNILAM-Solution:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Setup
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'

    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        java-version: ${{ inputs.java-version }}
        maven-version: 3.8.7

    - name: Install Yeoman
      run: | 
        npm install -g yo generator-code yeoman-generator
        npm install
        npm link 
      working-directory: generator/jdk11

    - name: Generate code
      run: yo jdk11-springboot
      working-directory: generator/jdk11

    - name: Install & Compile with maven
      run: mvn clean install -DskipTests
      working-directory: generator/jdk11/office-service
